### ISSUE TITLE
Add a way to update OPTD data

### ISSUE THREAD

**Issue by denisarnaud** [alexprengere/neobase#1]
Currently, the [Open Travel Data (OPTD)](https://github.com/opentraveldata/opentraveldata) POR data file, namely [`neobase/optd_por_public.csv`](https://github.com/alexprengere/neobase/blob/master/neobase/optd_por_public.csv), is static and rarely updated. Whereas the [original data file](https://github.com/opentraveldata/opentraveldata/blob/master/opentraveldata/optd_por_public.csv) is itself updated almost on a daily basis.

It is indeed good to ship Neobase with a version of that POR data file bundled, so as to quickstart right after installation of that component.
In addition, it should be easy to install a new version of that OPTD POR data file. For instance, a small script could do exactly that: download the [latest version of the OPTD POR data file](https://github.com/opentraveldata/opentraveldata/blob/master/opentraveldata/optd_por_public.csv) and drop in/replace the bundled one.

For examples on how to download the OPTD data files, the [Quality Assurance project](https://github.com/opentraveldata/quality-assurance) features [some such scripts](https://github.com/opentraveldata/quality-assurance/blob/master/checkers/DeliveryQuality.py#L48).

And if you feel you can improve those scripts, [contributions are welcome](https://github.com/opentraveldata/quality-assurance/compare)!

**Comment by alexprengere** [comment]
The installed package from PyPI is not updated often, this is correct. But the GitHub repository is updated several times a week, so using the GitHub remote `git+https://github.com/alexprengere/neobase.git#egg=neobase` in your requirements.txt will give you fresh data upon installation.

Finally, [this script](https://github.com/alexprengere/neobase/blob/master/update_data.sh) can be used to download the latest data locally, and it is possible to provide a custom file upon initialization:

```
N = NeoBase(open("local.csv"))
```

**Comment by denisarnaud** [comment]
Thanks for the answer!
Fair enough about the data updater. But couldn't it be integrated in a Python method within Neobase? It will become much simpler to always have fresh data :)

**Comment by alexprengere** [comment]
It could, but it can also be achieved very easily by users. Assuming Python3:

```python
URL = ('https://raw.githubusercontent.com/opentraveldata/opentraveldata/'
       'master/opentraveldata/optd_por_public.csv')

import urllib3
from io import StringIO
from neobase import NeoBase

r = urllib3.PoolManager().request("GET", URL)
N = NeoBase(StringIO(r.data.decode("utf8")))
N.get("PAR")
```
